services:
  db:
      image: mysql:8.0
      ports:
        - "3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        TZ: Asia/Taipei
        LANG: C.UTF-8
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 30s
        start_period: 40s
        timeout: 20s
        retries: 2

  app:
    build: ./app
    ports:
      - "5001:5000"
    depends_on:
       db:
        condition: service_healthy
